name: Build and push Docker image

on:
  push:
    branches:
      - main

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: ${{ vars.DOCKER_USERNAME }}/${{ github.event.repository.name }}:${{ github.run_number }}
          
  update-helm-chart:
    needs: build_and_push
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout Helm chart repository
      uses: actions/checkout@v4
      with:
        repository: ${{ github.repository_owner }}/argo-examples
        token: ${{ secrets.PAT_TOKEN }}

    - name: Update build number in values-dev.yaml
      run: |
        # Show current content for debugging
        echo "Current values-dev.yaml content:"
        cat helm-webapp/values-dev.yaml
        
        # Update the tag with GitHub run number
        sed -i "s/^tag: .*/tag: ${{ github.run_number }}/" helm-webapp/values-dev.yaml
        
        # Show updated content
        echo "Updated values-dev.yaml content:"
        cat helm-webapp/values-dev.yaml
        
        echo "Updated build number to ${{ github.run_number }}"

    - name: Commit and push changes
      run: |
        git config user.name "GitHub Action"
        git config user.email "action@github.com"
        
        # Check if there are changes to commit
        if git diff --quiet helm-webapp/values-dev.yaml; then
          echo "No changes detected in values-dev.yaml"
          exit 0
        else
          git add helm-webapp/values-dev.yaml
          git commit -m "Update build number to ${{ github.run_number }}"
          git push
        fi
